# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: thtest
version: '0.0.0'
github: "githubuser/thtest"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: thtest is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - template-haskell
  - persistent
  - text
  - bytestring
  - th-abstraction
  source-dirs: library

executables:
  thtest:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - thtest
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  thtest-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - thtest
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  thtest-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - thtest
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
